# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 20:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import posts.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170712_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='updater',
            field=models.ForeignKey(blank=True, null=True, on_delete=posts.models.empty_user, related_name='updated_answers_fk', to=settings.AUTH_USER_MODEL),
        ),
    ]
